import { test, expect } from '@playwright/test';

test('filters keep list and map aligned and detail uses last observation', async ({page})=>{
  await page.goto('/');
  await expect(page.getByRole('status')).toContainText('実データは未収集です');
  await expect(page.getByRole('status')).toContainText('過去の実店舗の閉店状況は検索できません');
  await expect(page.locator('.result-card')).toHaveCount(1);
  await page.getByLabel('都道府県').selectOption('東京都');
  await expect(page.locator('.result-card')).toHaveCount(0);
  await page.getByLabel('都道府県').selectOption('神奈川県');
  await expect(page.locator('.result-card')).toHaveCount(1);
  await expect(page.locator('.map-store-marker.closure')).toHaveCount(1);
  await expect(page.locator('.map-store-marker.seven')).toHaveCount(1);
  await expect(page.locator('.map-store-marker.closure img')).toHaveAttribute('src','/brand-logos/lawson.svg');
  await expect(page.locator('.map-store-marker.seven img')).toHaveAttribute('src','/brand-logos/seven-eleven.svg');
  await expect.poll(async()=>page.locator('.map-legend img').evaluateAll(images=>images.every(img=>(img as HTMLImageElement).naturalWidth>0))).toBe(true);
  await expect.poll(async()=>{
    const seven=await page.locator('.map-store-marker.seven').boundingBox();
    const closure=await page.locator('.map-store-marker.closure').boundingBox();
    if(!seven||!closure)return 0;
    return Math.hypot(seven.x+seven.width/2-closure.x-closure.width/2,seven.y+seven.height/2-closure.y-closure.height/2);
  }).toBeGreaterThan(45);
  await expect(page.getByRole('checkbox',{name:'FamilyMart'})).toBeChecked();
  await expect(page.getByRole('checkbox',{name:'LAWSON'})).toBeChecked();
  await page.getByRole('checkbox',{name:'LAWSON'}).uncheck();
  await expect(page.locator('.result-card')).toHaveCount(0);
  await expect(page.locator('.map-store-marker.closure')).toHaveCount(0);
  await expect(page.locator('.map-store-marker.seven')).toHaveCount(0);
  await page.getByRole('checkbox',{name:'LAWSON'}).check();
  await expect(page.locator('.result-card')).toHaveCount(1);
  await page.getByRole('checkbox',{name:'FamilyMart'}).uncheck();
  await expect(page.locator('.result-card')).toHaveCount(1);
  await page.getByRole('checkbox',{name:'FamilyMart'}).check();
  await page.getByText('状態の説明').click();
  await expect(page.getByText('前回は店舗データに存在し、最新の取得では見つからない店舗。')).toBeVisible();
  await page.getByText('状態の説明').click();
  await page.locator('.result-card').click();
  await expect(page.getByRole('dialog',{name:'店舗詳細'})).toBeVisible();
  await expect(page.getByText('神奈川県相模原市中央区中央1-1-2')).toBeVisible();
  await expect(page.locator('.map-distance')).toContainText('45m');
  await page.getByLabel('詳細を閉じる').click();
  await page.locator('.map-store-marker.seven').click();
  await expect(page.getByRole('dialog',{name:'店舗詳細'})).toBeVisible();
  await page.getByLabel('詳細を閉じる').click();
  await page.locator('.map-store-marker.closure').click();
  await expect(page.getByRole('dialog',{name:'店舗詳細'})).toBeVisible();
  await expect(page.locator('.map-distance')).toContainText('45m');
  await page.getByLabel('詳細を閉じる').click();
  await page.getByLabel('距離').selectOption('50');
  await expect(page.locator('.result-card')).toHaveCount(1);
  await page.getByLabel('距離').selectOption('500');
  await expect(page.locator('.result-card')).toHaveCount(1);
  await page.getByLabel('距離').selectOption('1000');
  await expect(page.locator('.result-card')).toHaveCount(1);
  await page.getByLabel('状態').selectOption('MISSING');
  await expect(page.locator('.result-card')).toHaveCount(0);
});

test('store map shows collected locations and a visible release version', async ({page})=>{
  await page.goto('/');
  await expect(page.getByRole('link',{name:'v0.4.5'})).toBeVisible();
  const version=await page.request.get('/api/version');
  expect((await version.json()).version).toBe('0.4.5');
  await page.getByRole('button',{name:'収録店舗マップ'}).click();
  await expect(page.getByRole('heading',{name:/収録店舗一覧/})).toContainText('2 件');
  await expect(page.locator('.store-result')).toHaveCount(2);
  await expect(page.locator('.map-current-marker')).toHaveCount(1);
  await expect(page.locator('.map-current-marker')).toHaveAttribute('aria-label','2件・拡大して表示');
  await page.getByRole('checkbox',{name:'ファミリーマート'}).uncheck();
  await expect(page.locator('.store-result')).toHaveCount(1);
  await expect(page.locator('.map-current-marker')).toHaveCount(1);
  await page.locator('.store-result').click();
  await expect(page.getByRole('dialog',{name:'収録店舗詳細'})).toContainText('セブン-イレブン 相模原中央店');
  await expect(page.getByRole('link',{name:'Googleマップで店舗を照合'})).toHaveAttribute('href',/google\.com\/maps\/search\/\?api=1&query=/);
});

test('observation period searches historical stores in both list and map', async ({page})=>{
  await page.goto('/');
  await page.getByRole('button',{name:'収録店舗マップ'}).click();
  await expect(page.locator('.store-result')).toHaveCount(2);
  await page.getByLabel('観測期間 開始').fill('2026-06-01');
  await page.getByLabel('観測期間 終了').fill('2026-06-01');
  await expect(page.getByRole('heading',{name:/期間内の観測店舗/})).toContainText('3 件');
  await expect(page.locator('.store-result')).toHaveCount(3);
  await expect(page.getByText('ローソン 相模原中央店')).toBeVisible();
  await expect(page.locator('.map-current-marker')).toHaveCount(1);
  await page.getByRole('button',{name:/ローソン（その他表記） 期間内に観測 ローソン 相模原中央店/}).click();
  await expect(page.getByRole('dialog',{name:'収録店舗詳細'})).toContainText('期間内の最終観測');
  await page.getByLabel('詳細を閉じる').click();
  await page.getByLabel('観測期間 開始').fill('2026-06-15');
  await page.getByLabel('観測期間 終了').fill('2026-06-15');
  await expect(page.locator('.store-result')).toHaveCount(2);
  await expect(page.getByText('ローソン 相模原中央店')).toHaveCount(0);
  await page.getByRole('button',{name:'期間を解除'}).click();
  await expect(page.getByRole('heading',{name:/収録店舗一覧/})).toContainText('2 件');
  const invalid=await page.request.get('/api/stores?from=2026-06-16&to=2026-06-15');
  expect(invalid.status()).toBe(400);
});
